version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/node-app
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 180
      runas: root

  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
      runas: root
