version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install

  build:
    commands:
      - echo "Running build step (if needed)..."
      - npm run build
      - echo "Preparing output directory..."
      - mkdir -p output
      - cp -r src/ public/ package.json output/

  post_build:
    commands:
      - echo "Build completed at $(date)"

artifacts:
  files:
    - output/**/*
    - appspec.yml
    - scripts/**/*
